extends: airbnb-base
plugins:
  - import

rules:
  # Code Quality
  eqeqeq:
    - error
    - always
  no-confusing-arrow:
    - error
    - allowParens: true
  no-constant-condition:
    - error
    - checkLoops: false
  no-undef:
    - off
  no-lonely-if:
    - warn
  no-console:
    - off
    - allow:
      - assert
      - error
  no-underscore-dangle:
    - warn
    - allowAfterThis: true
      allowAfterSuper: true
  class-methods-use-this:
    - off
  no-param-reassign:
    - off
  no-plusplus:
    - off
  no-else-return:
    - off

  # Code Style
  max-len:
    - error
    - code: 100
      ignoreUrls: true
  indent:
    - error
    - 2
    - ArrayExpression: first
      ObjectExpression: first
      MemberExpression: 1
      FunctionDeclaration:
        parameters: first
      FunctionExpression:
        parameters: first
      CallExpression:
        arguments: first
  camelcase:
    - error
    - properties: always
  curly:
    - off
  space-in-parens:
    - error
    - never
  arrow-parens:
    - error
    - as-needed
  arrow-body-style:
    - error
    - as-needed
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      functions: never